import { Geist, Geist_Mono, Rajdhani } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Shared/Navbar";
import Footer from "./Components/Shared/Footer";
import { ToastContainer } from "react-toastify";
import AuthProvider from "@/lib/AuthProvider"; // আপনার পাথ অনুযায়ী ইম্পোর্ট করুন

export const rajdhani = Rajdhani({
  subsets: ['latin'],
  weight: ['500', '600', '700'],
  variable: '--font-rajdhani',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AutoNest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* পুরো অ্যাপকে AuthProvider দিয়ে ঘিরে দিন */}
        <AuthProvider>
          <Navbar />
          <main>
            {children}
          </main>
          <Footer />
          <ToastContainer theme="dark" position="top-right" />
        </AuthProvider>
      </body>
    </html>
  );
}